### ISSUE TITLE
"Close Preview" keybinding doesn't work

### ISSUE THREAD

**Issue by 3xploiton3** [yzhang-gh/vscode-markdown#1368]
### What's the problem
**Close Preview** doesn't work with keybinding

### Screenshot
![image](https://github.com/yzhang-gh/vscode-markdown/assets/19517680/5ab95725-0d28-4931-b727-f0948a3fc6ef)
![image](https://github.com/yzhang-gh/vscode-markdown/assets/19517680/840e126c-b74b-44a8-959c-b813c5299646)

![image](https://github.com/yzhang-gh/vscode-markdown/assets/19517680/40375dc0-13a0-41ae-af30-b694cd1d8ecf)

**Comment by yzhang-gh** [comment]
You can use [this method](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) to help find out the reason.

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/5bd479d5-557c-4058-8757-e193712283b4)

**Comment by 3xploiton3** [comment]
troubleshooting log

<details>

>  [KeybindingService]: | Resolving ctrl+shift+[KeyV]
2023-12-17 19:49:14.063 [info] [KeybindingService]: \ From 3 keybinding entries, matched markdown.showPreview, when: !notebookEditorFocused && editorLangId == 'markdown', source: built-in extension vscode.markdown-language-features.
2023-12-17 19:49:14.063 [info] [KeybindingService]: + Invoking command markdown.showPreview.
2023-12-17 19:49:14.102 [error] Error: Unable to resolve filesystem provider with relative file path 'untitled:Untitled-1'
    at n.withProvider (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:645:17906)
    at n.doWatch (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:645:33033)
    at vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:645:32687
    at n.watch (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:645:32778)
    at v.$watch (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2175:12202)
    at m._doInvokeHandler (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1567:24876)
    at m._invokeHandler (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1567:24558)
    at m._receiveRequest (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1567:23328)
    at m._receiveOneMessage (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1567:22030)
    at o.value (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1567:20093)
    at d._deliver (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2465)
    at d.fire (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2784)
    at s.fire (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:616:17227)
    at K.onmessage (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:1663:10861)
2023-12-17 19:49:14.302 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
2023-12-17 19:49:31.687 [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
2023-12-17 19:49:31.689 [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
2023-12-17 19:49:31.690 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-12-17 19:49:31.723 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 17, key: Control
2023-12-17 19:49:31.724 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 5 ('Ctrl')
2023-12-17 19:49:31.724 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2023-12-17 19:49:32.148 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: KeyV, keyCode: 86, key: V
2023-12-17 19:49:32.149 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: KeyV, keyCode: 52 ('V')
2023-12-17 19:49:32.150 [info] [KeybindingService]: | Resolving ctrl+shift+[KeyV]
2023-12-17 19:49:32.150 [info] [KeybindingService]: \ From 3 keybinding entries, no when clauses matched the context.
2023-12-17 19:49:32.335 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
2023-12-17 19:49:58.361 [error] There are no commenting ranges at the current position.: Error: There are no commenting ranges at the current position.
    at N.addCommentAtLine (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2069:3423)
    at N.addOrToggleCommentAtLine (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2069:2827)
    at N.onEditorMouseUp (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2069:2450)
    at o.value (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:2068:25756)
    at j._deliver (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2465)
    at j._deliverQueue (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2556)
    at j.fire (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2891)
    at j.fire (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:744:25344)
    at de.onMouseUp (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:744:22678)
    at y.emitMouseUp (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:95:44051)
    at _.emitMouseUp (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:681:46633)
    at f._onMouseUp (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:719:17035)
    at vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:719:13775
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:714:41488)
2023-12-17 19:50:03.686 [info] [KeybindingService]: / Soft dispatching keyboard event
2023-12-17 19:50:03.687 [info] [KeybindingService]: | Resolving ctrl+shift+[KeyC]
2023-12-17 19:50:03.687 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.openNativeConsole, when: !terminalFocus, source: built-in.
2023-12-17 19:50:03.688 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: KeyC, keyCode: 67, key: C
2023-12-17 19:50:03.688 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: KeyC, keyCode: 33 ('C')
2023-12-17 19:50:03.689 [info] [KeybindingService]: | Resolving ctrl+shift+[KeyC]
2023-12-17 19:50:03.689 [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.terminal.openNativeConsole, when: !terminalFocus, source: built-in.
2023-12-17 19:50:03.689 [info] [KeybindingService]: + Invoking command workbench.action.terminal.openNativeConsole.
2023-12-17 19:50:03.707 [error] spawn xterm ENOENT: Error: spawn xterm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-17 19:50:03.954 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.


</details>

**Comment by yzhang-gh** [comment]
Thanks. I checked it and realized it is a known issue #1263 and has been fixed in the dev build. You can install the dev build from
https://github.com/yzhang-gh/vscode-markdown/actions/runs/7114681540/artifacts/1096290300
