### ISSUE TITLE
Markdown file fails to render

### ISSUE THREAD

**Issue by gmccullo** [yzhang-gh/vscode-markdown#808]
#### What is the problem?

I have one markdown file that consistently fails to render. Reloading with extensions disabled does not fix it. Sometimes shows the error message "An error occurred while loading view: markdown.preview". Here's the stacktrace from Log (Window):

[2020-09-08 11:43:21.375] [renderer1] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at f (c:\Users\gary\.vscode\extensions\yzhang.markdown-all-in-one-3.3.0\dist\extension.js:1:267054)
	at m (c:\Users\gary\.vscode\extensions\yzhang.markdown-all-in-one-3.3.0\dist\extension.js:1:264154)
	at g (c:\Users\gary\.vscode\extensions\yzhang.markdown-all-in-one-3.3.0\dist\extension.js:1:265846)
	at v.provideCodeLenses (c:\Users\gary\.vscode\extensions\yzhang.markdown-all-in-one-3.3.0\dist\extension.js:1:268610)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:678:391
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:136
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:108)
	at _.provideCodeLenses (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:678:362)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:640
	at K._withAdapter (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:698:331)
	at K.$provideCodeLenses (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:618)
	at m._doInvokeHandler (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:926)
	at m._invokeHandler (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:618)
	at m._receiveRequest (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:818:201)
	at m._receiveOneMessage (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:817:6)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:161
	at l.fire (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:494)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1007:179
	at l.fire (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:494)
	at t.PersistentProtocol._receiveMessage (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:244:17)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:67
	at l.fire (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at p.acceptChunk (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:949)
	at c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:301
	at Socket.t (c:\Users\gary\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:572)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

#### How can I reproduce it?

It happens consistently for me with one particular file.

#### Is there any error message in the console?

"An error occurred while loading view: markdown.preview" is printed in the preview window.

However if I toggle developer tools on, the problem goes away, which might indicate it's a race condition.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

It is hard to tell what is going wrong from the log message. Can you try to find a minimum reproducible file? It seems to be related to the TOC.

**Comment by gmccullo** [comment]
I've tried trimming down the file to a minimum reproduction but had no
luck. Github won't let me upload a .md file. I can email it to you if you
like. It's about 700 lines.

**Comment by yzhang-gh** [comment]
You can compress it as a `zip` file so you can upload it. Or just send it to yzhang.lifeAToutlook.com
