### ISSUE TITLE
Markdown preview fails when connected to WSL2

### ISSUE THREAD

**Issue by yuhlzu** [yzhang-gh/vscode-markdown#868]
## Problem
vscode连接WSL2，预览md文件失败

## How to reproduce

点右上角打开预览

## Error message in the console
```
  ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at f (/home/yuh/.vscode-server/extensions/yzhang.markdown-all-in-one-3.4.0/dist/extension.js:1:296405)
	at p (/home/yuh/.vscode-server/extensions/yzhang.markdown-all-in-one-3.4.0/dist/extension.js:1:293505)
	at g (/home/yuh/.vscode-server/extensions/yzhang.markdown-all-in-one-3.4.0/dist/extension.js:1:295197)
	at v.provideCodeLenses (/home/yuh/.vscode-server/extensions/yzhang.markdown-all-in-one-3.4.0/dist/extension.js:1:297961)
	at b.provideCodeLenses (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:775:662)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:797:370
	at q._withAdapter (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:796:10)
	at q.$provideCodeLenses (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:797:348)
	at m._doInvokeHandler (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:915:201)
	at m._receiveOneMessage (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:914:6)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:1118:104
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by yzhang-gh** [comment]
能安装[调试版 (`debug.vsix`)](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) 然后复制一下错误信息吗？

**Comment by Lemmingh** [comment]
这个日志我很眼熟，应该是 TOC 抛出来的：
https://github.com/yzhang-gh/vscode-markdown/blob/eff0d51e5c271c9fafaa3dfff144cc7c7ae4e7da/src/toc.ts#L322-L323

很可能跟 Markdown 预览无关。

**Comment by yuhlzu** [comment]
> 这个日志我很眼熟，应该是 TOC 抛出来的：
> https://github.com/yzhang-gh/vscode-markdown/blob/eff0d51e5c271c9fafaa3dfff144cc7c7ae4e7da/src/toc.ts#L322-L323
> 
> 很可能跟 Markdown 预览无关。

确实没关系，我卸载了这个插件，还是无法预览，然后这样报错

```
  ERR Cannot read property 'resource' of undefined: TypeError: Cannot read property 'resource' of undefined
	at c.deserializeWebviewPanel (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/extensions/markdown-language-features/dist/extension.js:1:74039)
	at k.$deserializeWebviewPanel (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:898:567)
	at m._doInvokeHandler (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:915:252)
	at m._receiveOneMessage (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:914:201)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:1118:104
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by Lemmingh** [comment]
> ```
> at c.deserializeWebviewPanel (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/extensions/markdown-language-features/dist/extension.js:1:74039)
> ```

这句是 VS Code 内置的 Markdown Language Features (`vscode.markdown-language-features`) 的 webview panel 管理抛出的资源加载错误。那么，应该是 VS Code 的内部问题。

**Comment by yuhlzu** [comment]
> > ```
> > at c.deserializeWebviewPanel (/home/yuh/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/extensions/markdown-language-features/dist/extension.js:1:74039)
> > ```
> 
> 这句是 VS Code 内置的 Markdown Language Features (`vscode.markdown-language-features`) 的 webview panel 管理抛出的资源加载错误。那么，应该是 VS Code 的内部问题。

我关闭了v2rayN以后，预览就没问题了，暂时先这样解决吧

**Comment by Lemmingh** [comment]
VS Code 的 webview 跟代理有点冲突的样子：
https://github.com/microsoft/vscode/labels/webview

跟你的情况最相似的几个：
https://github.com/microsoft/vscode/issues/101272
https://github.com/microsoft/vscode/issues/103884
https://github.com/microsoft/vscode/issues/102284#issuecomment-657432570

**Comment by yuhlzu** [comment]
> VS Code 的 webview 跟代理有点冲突的样子：
> https://github.com/microsoft/vscode/labels/webview
> 
> 跟你的情况最相似的几个：
> [microsoft/vscode#101272](https://github.com/microsoft/vscode/issues/101272)
> [microsoft/vscode#103884](https://github.com/microsoft/vscode/issues/103884)
> [microsoft/vscode#102284 (comment)](https://github.com/microsoft/vscode/issues/102284#issuecomment-657432570)

我把代理换成  clash for windows好了，感谢
